/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

  GtkWidget *window;
  GtkWidget *table;
  GtkWidget *label_ref;
  GtkWidget *label_rref;
  GtkWidget *label_cl;
  GtkWidget *label_rcl;
  GtkWidget *label_a0;
  GtkWidget *label_ov;
  GtkObject *ref0_adj;
  GtkWidget *ref0;
  GtkObject *ref1_adj;
  GtkWidget *ref1;
  GtkObject *ref2_adj;
  GtkWidget *ref2;
  GtkWidget *rref0;
  GtkWidget *rref1;
  GtkWidget *rref2;
  GtkObject *cl0_adj;
  GtkWidget *cl0;
  GtkObject *cl1_adj;
  GtkWidget *cl1;
  GtkObject *cl2_adj;
  GtkWidget *cl2;
  GtkWidget *rcl0;
  GtkWidget *rcl1;
  GtkWidget *rcl2;
  GtkWidget *a00;
  GtkWidget *a01;
  GtkWidget *a02;
  GtkWidget *out0;
  GtkWidget *out1;
  GtkWidget *out2;
  GtkWidget *update;
  GtkWidget *quit;

GtkWidget*
create_window (void)
{
  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window, "window");
  gtk_window_set_title (GTK_WINDOW (window), _("GTK console"));

  table = gtk_table_new (5, 6, FALSE);
  gtk_widget_set_name (table, "table");
  gtk_widget_show (table);
  gtk_container_add (GTK_CONTAINER (window), table);
  gtk_container_set_border_width (GTK_CONTAINER (table), 10);
  gtk_table_set_row_spacings (GTK_TABLE (table), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table), 22);

  label_ref = gtk_label_new (_("Reference value (V)"));
  gtk_widget_set_name (label_ref, "label_ref");
  gtk_widget_show (label_ref);
  gtk_table_attach (GTK_TABLE (table), label_ref, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_ref), GTK_JUSTIFY_CENTER);

  label_rref = gtk_label_new (_("Stored reference"));
  gtk_widget_set_name (label_rref, "label_rref");
  gtk_widget_show (label_rref);
  gtk_table_attach (GTK_TABLE (table), label_rref, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_rref), GTK_JUSTIFY_CENTER);

  label_cl = gtk_label_new (_("Current limit (mA)"));
  gtk_widget_set_name (label_cl, "label_cl");
  gtk_widget_show (label_cl);
  gtk_table_attach (GTK_TABLE (table), label_cl, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_cl), GTK_JUSTIFY_CENTER);

  label_rcl = gtk_label_new (_("Stored current limit"));
  gtk_widget_set_name (label_rcl, "label_rcl");
  gtk_widget_show (label_rcl);
  gtk_table_attach (GTK_TABLE (table), label_rcl, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_rcl), GTK_JUSTIFY_CENTER);

  label_a0 = gtk_label_new (_("Analog 0 (V)"));
  gtk_widget_set_name (label_a0, "label_a0");
  gtk_widget_show (label_a0);
  gtk_table_attach (GTK_TABLE (table), label_a0, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_a0), GTK_JUSTIFY_CENTER);

  label_ov = gtk_label_new (_("Output voltage"));
  gtk_widget_set_name (label_ov, "label_ov");
  gtk_widget_show (label_ov);
  gtk_table_attach (GTK_TABLE (table), label_ov, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_ov), GTK_JUSTIFY_CENTER);

  ref0_adj = gtk_adjustment_new (12, 0, 16, 0.10000000149, 10, 10);
  ref0 = gtk_spin_button_new (GTK_ADJUSTMENT (ref0_adj), 1, 1);
  gtk_widget_set_name (ref0, "ref0");
  gtk_widget_show (ref0);
  gtk_table_attach (GTK_TABLE (table), ref0, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ref0), TRUE);

  ref1_adj = gtk_adjustment_new (5, 0, 16, 0.10000000149, 10, 10);
  ref1 = gtk_spin_button_new (GTK_ADJUSTMENT (ref1_adj), 1, 1);
  gtk_widget_set_name (ref1, "ref1");
  gtk_widget_show (ref1);
  gtk_table_attach (GTK_TABLE (table), ref1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ref1), TRUE);

  ref2_adj = gtk_adjustment_new (3.29999995232, 0, 16, 0.10000000149, 10, 10);
  ref2 = gtk_spin_button_new (GTK_ADJUSTMENT (ref2_adj), 1, 1);
  gtk_widget_set_name (ref2, "ref2");
  gtk_widget_show (ref2);
  gtk_table_attach (GTK_TABLE (table), ref2, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ref2), TRUE);

  rref0 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (rref0, "rref0");
  gtk_widget_show (rref0);
  gtk_table_attach (GTK_TABLE (table), rref0, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rref0), 0, 0.5);

  rref1 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (rref1, "rref1");
  gtk_widget_show (rref1);
  gtk_table_attach (GTK_TABLE (table), rref1, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rref1), 0, 0.5);

  rref2 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (rref2, "rref2");
  gtk_widget_show (rref2);
  gtk_table_attach (GTK_TABLE (table), rref2, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rref2), 0, 0.5);

  cl0_adj = gtk_adjustment_new (1000, 0, 1000, 1, 10, 10);
  cl0 = gtk_spin_button_new (GTK_ADJUSTMENT (cl0_adj), 1, 0);
  gtk_widget_set_name (cl0, "cl0");
  gtk_widget_show (cl0);
  gtk_table_attach (GTK_TABLE (table), cl0, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (cl0), TRUE);

  cl1_adj = gtk_adjustment_new (1000, 0, 1000, 1, 10, 10);
  cl1 = gtk_spin_button_new (GTK_ADJUSTMENT (cl1_adj), 1, 0);
  gtk_widget_set_name (cl1, "cl1");
  gtk_widget_show (cl1);
  gtk_table_attach (GTK_TABLE (table), cl1, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (cl1), TRUE);

  cl2_adj = gtk_adjustment_new (1000, 0, 1000, 1, 10, 10);
  cl2 = gtk_spin_button_new (GTK_ADJUSTMENT (cl2_adj), 1, 0);
  gtk_widget_set_name (cl2, "cl2");
  gtk_widget_show (cl2);
  gtk_table_attach (GTK_TABLE (table), cl2, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  rcl0 = gtk_label_new (_("0 mA"));
  gtk_widget_set_name (rcl0, "rcl0");
  gtk_widget_show (rcl0);
  gtk_table_attach (GTK_TABLE (table), rcl0, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rcl0), 0, 0.5);

  rcl1 = gtk_label_new (_("0 mA"));
  gtk_widget_set_name (rcl1, "rcl1");
  gtk_widget_show (rcl1);
  gtk_table_attach (GTK_TABLE (table), rcl1, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rcl1), 0, 0.5);

  rcl2 = gtk_label_new (_("0 mA"));
  gtk_widget_set_name (rcl2, "rcl2");
  gtk_widget_show (rcl2);
  gtk_table_attach (GTK_TABLE (table), rcl2, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rcl2), 0, 0.5);

  a00 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (a00, "a00");
  gtk_widget_show (a00);
  gtk_table_attach (GTK_TABLE (table), a00, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (a00), 0, 0.5);

  a01 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (a01, "a01");
  gtk_widget_show (a01);
  gtk_table_attach (GTK_TABLE (table), a01, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (a01), 0, 0.5);

  a02 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (a02, "a02");
  gtk_widget_show (a02);
  gtk_table_attach (GTK_TABLE (table), a02, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (a02), 0, 0.5);

  out0 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (out0, "out0");
  gtk_widget_show (out0);
  gtk_table_attach (GTK_TABLE (table), out0, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (out0), 0, 0.5);

  out1 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (out1, "out1");
  gtk_widget_show (out1);
  gtk_table_attach (GTK_TABLE (table), out1, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (out1), 0, 0.5);

  out2 = gtk_label_new (_("0 V"));
  gtk_widget_set_name (out2, "out2");
  gtk_widget_show (out2);
  gtk_table_attach (GTK_TABLE (table), out2, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (out2), 0, 0.5);

  update = gtk_button_new_with_mnemonic (_("Update"));
  gtk_widget_set_name (update, "update");
  gtk_widget_show (update);
  gtk_table_attach (GTK_TABLE (table), update, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  quit = gtk_button_new_with_mnemonic (_("Exit"));
  gtk_widget_set_name (quit, "quit");
  gtk_widget_show (quit);
  gtk_table_attach (GTK_TABLE (table), quit, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) update, "clicked",
                    G_CALLBACK (on_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, table, "table");
  GLADE_HOOKUP_OBJECT (window, label_ref, "label_ref");
  GLADE_HOOKUP_OBJECT (window, label_rref, "label_rref");
  GLADE_HOOKUP_OBJECT (window, label_cl, "label_cl");
  GLADE_HOOKUP_OBJECT (window, label_rcl, "label_rcl");
  GLADE_HOOKUP_OBJECT (window, label_a0, "label_a0");
  GLADE_HOOKUP_OBJECT (window, label_ov, "label_ov");
  GLADE_HOOKUP_OBJECT (window, ref0, "ref0");
  GLADE_HOOKUP_OBJECT (window, ref1, "ref1");
  GLADE_HOOKUP_OBJECT (window, ref2, "ref2");
  GLADE_HOOKUP_OBJECT (window, rref0, "rref0");
  GLADE_HOOKUP_OBJECT (window, rref1, "rref1");
  GLADE_HOOKUP_OBJECT (window, rref2, "rref2");
  GLADE_HOOKUP_OBJECT (window, cl0, "cl0");
  GLADE_HOOKUP_OBJECT (window, cl1, "cl1");
  GLADE_HOOKUP_OBJECT (window, cl2, "cl2");
  GLADE_HOOKUP_OBJECT (window, rcl0, "rcl0");
  GLADE_HOOKUP_OBJECT (window, rcl1, "rcl1");
  GLADE_HOOKUP_OBJECT (window, rcl2, "rcl2");
  GLADE_HOOKUP_OBJECT (window, a00, "a00");
  GLADE_HOOKUP_OBJECT (window, a01, "a01");
  GLADE_HOOKUP_OBJECT (window, a02, "a02");
  GLADE_HOOKUP_OBJECT (window, out0, "out0");
  GLADE_HOOKUP_OBJECT (window, out1, "out1");
  GLADE_HOOKUP_OBJECT (window, out2, "out2");
  GLADE_HOOKUP_OBJECT (window, update, "update");
  GLADE_HOOKUP_OBJECT (window, quit, "quit");

  return window;
}

