all:
	arm-none-eabi-as arm.s -o arm.o
	arm-none-eabi-gcc -Wall -O1 -g3 -marm -mcpu=arm926ej-s -o main.o main.c
	arm-none-eabi-ld -Ttext=0 -Tdata=0x20000000 -o arm arm.o main.o
	arm-none-eabi-objdump -dSh arm > arm.list
