all:
	arm-none-eabi-as cortex-m3.s -o cortex-m3.o
	arm-none-eabi-gcc -Wall -O1 -g3 -mthumb -mcpu=cortex-m3 -o main.o main.c
	arm-none-eabi-ld -Ttext=0 -Tdata=0x20000000 -o cortex-m3 cortex-m3.o main.o
	arm-none-eabi-objdump -dSh cortex-m3 > cortex-m3.list
